language: rust
env:
  global:
    - RUSTFLAGS='-F warnings'
    - RUST_BACKTRACE=full
stages:
  - Check
  - Test
jobs:
  include:
    - stage: Check
      name: Format
      install: cargo fmt --version || rustup component add rustfmt
      script: cargo fmt --all -- --check
    - stage: Check
      name: Clippy
      install: cargo clippy --version || rustup component add clippy
      script: cargo clippy -- --deny warnings
    - stage: Test
      os: linux
    - stage: Test
      os: osx
    - stage: Test
      os: windows
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
