name: CI
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]
defaults:
  run:
    shell: bash
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: full
jobs:
  rustfmt:
    name: Checks / Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: cargo fmt --version || rustup component add rustfmt
      - name: Run
        run: cargo fmt --all -- --check
  clippy:
    name: Checks / Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: cargo clippy --version || rustup component add clippy
      - name: Run
        run: cargo clippy --locked -- --deny warnings
  test:
    name: Tests / Build & Test
    needs: [ rustfmt, clippy ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [ linux ]
        include:
          - build: linux
            os: ubuntu-latest
            rust: 1.48.0
      fail-fast: true
      max-parallel: 3
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose --all
      - name: Test
        run: cargo test --verbose --all
